# Generated by Django 3.1.3 on 2020-12-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_seo_tags', '0002_auto_20201206_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='seodefault',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
