# Generated by Django 3.1.4 on 2020-12-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_seo_tags', '0004_seodefault_twitter_handle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seodefault',
            old_name='twitter_handle',
            new_name='twitter_site_handle',
        ),
    ]
