# Generated by Django 3.1.4 on 2020-12-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
