# Generated by Django 3.1.4 on 2020-12-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201210_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='desc',
            new_name='description',
        ),
    ]
